import "./styles/globals.css";
import type { Metadata } from "next";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/Footer";
import { Montserrat } from "next/font/google";
import "swiper/css";
import 'swiper/css/effect-coverflow';

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <main>
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
