import "./styles/globals.css";
import type { Metadata } from "next";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/Footer";
import localFont from "next/font/local";
import "swiper/css";
import "swiper/css/effect-coverflow";

const Mont = localFont({
  src: [
    {
      path: "./fonts/Mont/Mont-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Mont/Mont-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Mont/Mont-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Mont/Mont-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Mont/Mont-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Mont/Mont-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Mont/Mont-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-mont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${Mont.variable}`}>
      <body>
        <main>
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
